### PR TITLE
Ran the rake task to pull in the latest jsoneditor assets (5.24.6).

### PR DESCRIPTION
**Pull request by mjrudowsky**
Javier,
I have followed the instructions to bring in the latest jsoneditor assets. Please let me know if anything else is required.

Thank you!
-Mike

### CODE REVIEW

**Comment by javierjulio** [comment]
@mjrudowsky awesome thanks! 🙌🏻 I'll get this out shortly in a new release for you. Thanks again for contributing!

**Comment by javierjulio** [comment]
@mjrudowsky I released jsoneditor-rails 1.0.2 for you. Give it a try and let me know how it works out. Thanks again! 👍🏻

**Comment by mjrudowsky** [comment]
@javierjulio Just a note to let you know it's working great! Thanks for the effort and quick response!

**Comment by javierjulio** [comment]
@mjrudowsky awesome thanks! No problem at all, happy to help. 😄

**Pull request merged**
