### PR TITLE
Bumped jsoneditor to version 5.9

### PR DESCRIPTION
**Pull request by dmitryshagin**

### CODE REVIEW

**Comment by javierjulio** [comment]
@dmitryshagin thanks for doing this! Just to confirm you ran the built in rake task to update the files?

**Comment by dmitryshagin** [comment]
Yep, I just run rake task and bumped version to 1.0.1

**Comment by javierjulio** [comment]
@dmitryshagin thanks so much for doing this! I appreciate it. I'll get this out shortly. Going to start up a changelog first.

**Comment by javierjulio** [comment]
@dmitryshagin the 1.0.1 release is now out. Thanks again!

**Pull request merged**
